### ISSUE TITLE
Crash after tie game

### ISSUE THREAD

**Issue by zrbecker** [heyoni/tictactoe#4]
Looks like the computer kept trying to play the game.

Here is the output
https://imgur.com/a/cJU0T

**Comment by dltacube** [comment]
Oh that's weird and a really good find! It's trying to use the move variable even though there are none -_-

**Comment by dltacube** [comment]
I think I fixed several game-ending problems with my last commit that had to do with how python handles mutable default variables in functions. 

It was fun to fix, so thank you for pointing this out :D
